apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoguard-ml-api
  namespace: autoguard-system
  labels:
    app.kubernetes.io/part-of: k8s-autoguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: autoguard-ml-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoguard-remediation
  namespace: autoguard-system
  labels:
    app.kubernetes.io/part-of: k8s-autoguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: autoguard-remediation
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
