config:
  clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
  snippets:
    scrapeConfigs: |
      - job_name: autoguard-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels:
              - __meta_kubernetes_namespace
            regex: autoguard-system|autoguard-demo|falco|falco-demo
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__

initContainer:
  - name: raise-inotify-limit
    image: docker.io/busybox:1.36.1
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - sysctl -w fs.inotify.max_user_instances=1024
    securityContext:
      privileged: true

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
