apiVersion: v1
kind: Namespace
metadata:
  name: autoguard-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: autoguard-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/part-of: autoguard-policy-demo
    spec:
      containers:
        - name: api
          image: quay.io/cilium/json-mock:v1.4.1@sha256:6a66df90808a39c02e7a9d58af7bf0e54d8f8b7d4bc528f48c891969a7049195
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: autoguard-demo
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-client
  namespace: autoguard-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trusted-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trusted-client
        access: trusted
    spec:
      containers:
        - name: client
          image: quay.io/cilium/alpine-curl:v1.10.0@sha256:913e8c9f3d960dde03882defa0edd3a919d529c2eb167caa7f54194528bde364
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: untrusted-client
  namespace: autoguard-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: untrusted-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: untrusted-client
        access: untrusted
    spec:
      containers:
        - name: client
          image: quay.io/cilium/alpine-curl:v1.10.0@sha256:913e8c9f3d960dde03882defa0edd3a919d529c2eb167caa7f54194528bde364
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
